---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/responses":
    get:
      summary: list responses
      responses:
        '200':
          description: successful
    post:
      summary: create response
      responses:
        '200':
          description: successful
  "/responses/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show response
      responses:
        '200':
          description: successful
    patch:
      summary: update response
      responses:
        '200':
          description: successful
    put:
      summary: update response
      responses:
        '200':
          description: successful
    delete:
      summary: delete response
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost
